Reformat source to follow style guidelines

diff --git a/bin/varrick b/bin/varrick
--- a/bin/varrick
+++ b/bin/varrick
@@ -164,9 +164,10 @@ _d8e1_OPT_SUMMARY=0
 _d8e1_OPT_ESCAPE=0
 
 # Parse options.
-_d8e1_TEMP=$(getopt --options c,e,h,m,p,s,u,v,x \
-                    --long check,escape,help,missing,no-expand,preprocess,summary,usage,version \
-                    --name "varrick" -- "$@")
+_d8e1_TEMP=$(getopt \
+  --options c,e,h,m,p,s,u,v,x \
+  --long check,escape,help,missing,no-expand,preprocess,summary,usage,version \
+  --name "varrick" -- "$@")
 
 if [ $? != 0 ]; then echo "Terminating..." >&2; exit 1; fi
 eval set -- "$_d8e1_TEMP"
@@ -189,7 +190,7 @@ done
 
 # Options --missing and --no-expand are mutually exclusive.
 if [ "$_d8e1_OPT_MISSING" -eq 1 ] && [ "$_d8e1_OPT_EXPAND" -eq 1 ]; then
-  echo "Error: \`--missing' (-m) and \`--no-expand' (-e) cannot be specified at the same time!"
+  echo "Error: \`--missing' (-m) and \`--no-expand' (-e) are mutually exclusive!"
   exit 1
 fi
 
@@ -209,7 +210,8 @@ if [ "$_d8e1_INPUT_SRC" == 'character special file' ]; then
 
   # If output is a directory, use the input file's name w/o the `.tmpl' suffix.
   if [ "$#" -eq 2 ]; then
-    _d8e1_DEST="$([ -d "$2" ] && echo "$2/$(basename "${1%.tmpl}")" || echo "$2")"
+    _d8e1_DEST="$( [ -d "$2" ] && echo "$2/$(basename "${1%.tmpl}")" \
+                               || echo "$2" )"
   fi
 
   if [ ! -e "$1" ]; then
@@ -292,10 +294,9 @@ else
   # Not quoting `$SHELL_FORMAT' allows not passing the argument if it's not set.
   if [ "$_d8e1_OPT_ESCAPE" -eq 1 ]; then
     escape_vars "$(get_defined "$_d8e1_INPUT")"
-    _d8e1_OUTPUT="$(echo "$_d8e1_INPUT" \
-                      | escape \
-                      | envsubst $_d8e1_SHELL_FORMAT \
-                      | unescape)"
+    _d8e1_OUTPUT="$(echo "$_d8e1_INPUT" | escape \
+                                        | envsubst $_d8e1_SHELL_FORMAT \
+                                        | unescape)"
   else
     _d8e1_OUTPUT="$(echo "$_d8e1_INPUT" | envsubst $_d8e1_SHELL_FORMAT)"
   fi
