Add option to check templates for invalid escaping

diff --git a/expand-template b/expand-template
--- a/expand-template
+++ b/expand-template
@@ -36,6 +36,9 @@ _d8e1_OPT_ESCAPE=0
 # Print a list of variable referenced and escaped (-s, --summary).
 _d8e1_OPT_SUMMARY=0
 
+# Print list of invalid escapings if any (-v, --verify).
+_d8e1_OPT_CHECK=0
+
 
 ################################################################################
 #                                 HANDLE OPTIONS
@@ -62,6 +65,7 @@ Options:
   -e, --no-expand   Do not expand variables that are not defined. Forbids \`-m'.
   -x, --escape      Allow escaping variable references with a backslash.
   -s, --summary     Print a list of referenced and escaped variables and exit.
+  -c, --check       Look for invalid escape sequences and exit.
 
 Variable References:
   References of the form \`\$var' and \`\${var}' can be substituted with the value
@@ -102,8 +106,8 @@ Caveat:
 EOUSAGE
 }
 
-_d8e1_TEMP=$(getopt --options m,e,x,s \
-                    --long missing,no-expand,escape,summary \
+_d8e1_TEMP=$(getopt --options m,e,x,s,c \
+                    --long missing,no-expand,escape,summary,check \
                     --name "$(basename "$0")" -- "$@")
 
 if [ $? != 0 ]; then echo "Terminating..." >&2; exit 1; fi
@@ -115,6 +119,7 @@ while true; do
     -e|--no-expand) _d8e1_OPT_EXPAND=1; shift;;
     -x|--escape) _d8e1_OPT_ESCAPE=1; shift;;
     -s|--summary) _d8e1_OPT_SUMMARY=1; shift;;
+    -c|--check) _d8e1_OPT_CHECK=1; shift;;
     --) shift; break;;
     *) echo "Internal error!"; exit 1;;
   esac
@@ -327,6 +332,7 @@ get_defined () {
 escape () {
   local name='[a-zA-Z_][a-zA-Z_0-9]*'
 
+  # FIXME(ztombol): #1 should be done by the user.
   # 1. $\var   -> $\\var
   # 2. $\{var} -> $\\{var}
   # 3. (even x \)\$var   -> (even x \)$\var
@@ -383,6 +389,51 @@ escape_vars () {
   done
 }
 
+# Check that all escape sequences are valid in the given template. Lines
+# containing invalid escape sequences are printed along with their line numbers.
+#
+# Globals:
+#   none
+# Arguments:
+#   $1 - template string
+# Input:
+#   none
+# Outputs:
+#   STDOUT - escaping errors with line numbers if any
+# Returns:
+#   0 - correct escaping
+#   1 - otherwise
+check_esc () {
+  local input="$1"
+
+  local error=0
+  local line_no=0
+  while read -r line; do
+    : $((++line_no))
+    # Mutually exclusive patterns matching:
+    # 1. (odd * `\') + (not a `$')
+    # 2. (odd * `\') + $ + (not a `{' or variable name character)
+    # 3. (odd * `\') + ${ + (not a variable name character)
+    # 4. (odd * `\') + ${ + (variable name characters) + (not a `}' or a variable name character)
+    local match="$(echo "$line" \
+      | sed -nr -e '/(^|[^\])(\\\\)*\\([^\$]|$)/p' \
+                -e '/(^|[^\])(\\\\)*\\\$([^{a-zA-Z_]|$)/p' \
+                -e '/(^|[^\])(\\\\)*\\\$\{([^a-zA-Z_]|$)/p' \
+                -e '/(^|[^\])(\\\\)*\\\$\{[a-zA-Z_][a-zA-Z_0-9]*([^}a-zA-Z_0-9]|$)/p'
+    )"
+    if [ -n "$match" ]; then
+      if [ "$error" -eq 0 ]; then
+        echo 'Error: Invalid escaping in the following lines:'
+        error=1
+      fi
+      echo "$line_no: $match"
+    fi
+  done <<< "$input"
+
+  [ "$error" -eq 0 ] && echo 'Everything looks good!'
+  return $error
+}
+
 
 ################################################################################
 #                                      MAIN
@@ -402,6 +453,11 @@ if [ "$_d8e1_OPT_SUMMARY" -eq 1 ]; then
     printf "%s\n" "${_d8e1_REFERENCED[@]}"
   fi
   exit 0
+fi
+
+if [ "$_d8e1_OPT_CHECK" -eq 1 ]; then
+  check_esc "$_d8e1_INPUT"
+  exit $?
 fi
 
 if [ "$_d8e1_OPT_MISSING" -eq 1 ]; then
